In [9]:
import numpy as np

In [4]:
!pwd

/Users/miguelcamargorojas/Documents/UP/PDI-Ago-dic24/Semana II


In [6]:
# pip install <package>
!python3 -V

Python 3.11.6


In [7]:
!python3 -m pip list

Package                      Version
---------------------------- ---------
absl-py                      2.0.0
appnope                      0.1.3
asttokens                    2.2.1
astunparse                   1.6.3
backcall                     0.2.0
cachetools                   5.3.1
certifi                      2023.7.22
cffi                         1.16.0
charset-normalizer           3.2.0
comm                         0.1.3
debugpy                      1.6.7
decorator                    5.1.1
docutils                     0.20.1
executing                    1.2.0
flatbuffers                  23.5.26
gast                         0.5.4
google-auth                  2.23.2
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.58.0
h5py                         3.9.0
idna                         3.4
ipykernel                    6.23.1
ipython                      8.13.2
jedi                         0.18.2
jupyter_client               8.2.0
jup

In [8]:
!python3 -m pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [11]:
# ND-Arreglos
arr1 = np.array([1, 2, 3])

In [12]:
print(arr1)

[1 2 3]


In [13]:
type(arr1)

numpy.ndarray

In [14]:
dir([])

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [15]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [20]:
lista1 = [1, 1.1, "", True]
np.asarray(lista1)

array(['1', '1.1', '', 'True'], dtype='<U32')

In [21]:
arr2 = np.asarray([1, 2, 3, 4, 5])

In [22]:
arr2.shape

(5,)

In [23]:
arr2.dtype

dtype('int64')

In [24]:
len(arr2)

5

In [25]:
# Lista de listas
lista2 = [[1, 2, 3], [4, 5, 6]]

In [26]:
type(lista2)

list

In [30]:
lista2[0][0]

1

In [31]:
arr3 = np.asarray(lista2)

In [32]:
type(arr3)

numpy.ndarray

In [33]:
len(arr3)

2

In [34]:
arr3.shape

(2, 3)

In [35]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr3[0, 1]

2

In [41]:
arr3[:, :2]

array([[1, 2],
       [4, 5]])

In [42]:
arr3.size

6

In [43]:
arr3.min()

1

In [44]:
arr3.max()

6

In [47]:
800 * 800 * 3

1920000

In [48]:
arr3.mean()

3.5

In [49]:
arr3.std()

1.707825127659933

In [50]:
np.median(arr3)

3.5

In [51]:
# O.Arit.
arr3 + 1 # Element-wise

array([[2, 3, 4],
       [5, 6, 7]])

In [52]:
arr3 - 10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [54]:
arr3 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [55]:
arr3 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [56]:
arr3 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
arr3 + arr3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# Copiar arreglos
tmp = arr3

In [60]:
tmp

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr3[0, 0] = 100

In [62]:
arr3

array([[100,   2,   3],
       [  4,   5,   6]])

In [63]:
tmp

array([[100,   2,   3],
       [  4,   5,   6]])

In [64]:
# MÉTODO IDEAL
tmp = arr3.copy()

In [65]:
arr3[0, 0] = 500

In [66]:
arr3

array([[500,   2,   3],
       [  4,   5,   6]])

In [67]:
tmp

array([[100,   2,   3],
       [  4,   5,   6]])

### Random

In [68]:
np.random.random()

0.6551032245437831

In [81]:
np.random.randint(10, size=(10, 10))

array([[8, 4, 4, 9, 8, 8, 8, 9, 2, 1],
       [8, 7, 2, 8, 7, 2, 2, 3, 7, 7],
       [5, 1, 1, 8, 3, 7, 1, 7, 2, 7],
       [7, 0, 5, 0, 6, 2, 4, 2, 4, 7],
       [6, 8, 2, 4, 6, 4, 0, 5, 5, 9],
       [2, 7, 4, 1, 0, 0, 5, 2, 4, 2],
       [3, 2, 5, 4, 2, 8, 9, 0, 8, 2],
       [1, 3, 3, 1, 2, 1, 3, 4, 9, 5],
       [8, 6, 6, 9, 0, 2, 3, 1, 8, 9],
       [6, 9, 2, 5, 2, 2, 0, 3, 2, 0]])

In [82]:
np.random.seed(123)

In [84]:
np.random.randint(10, size=(10, 10))

array([[5, 8, 6, 8, 9, 1, 0, 3, 1, 3],
       [4, 7, 6, 1, 4, 3, 3, 7, 6, 8],
       [6, 4, 4, 7, 0, 0, 9, 8, 8, 4],
       [8, 6, 1, 6, 8, 7, 9, 1, 7, 1],
       [7, 9, 8, 7, 1, 3, 1, 8, 7, 5],
       [1, 2, 5, 2, 2, 9, 3, 2, 6, 7],
       [9, 1, 3, 8, 3, 7, 9, 9, 3, 3],
       [5, 6, 0, 8, 7, 7, 4, 4, 5, 0],
       [8, 9, 2, 5, 1, 5, 9, 2, 4, 3],
       [0, 3, 7, 7, 2, 5, 1, 7, 5, 9]])